# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a715841c3aa7294dbaba38e72f6b3ca1d49d5e9307c9311fe3791afe1a1eb4349aff437241e0de3ee971fe0a63b9ac19cf3d33fd699924d9bf26f2e2ac74e681

test:
  secret_key_base: b2d8a2fb6e0ab6cf9696c767ca452ca5a23a125aba62b327c59406e5eefb1dbe6faa57630345c4dad48fdacf90610486b0b62bff54378d387d3cad9a16b89026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
